# -*- coding: utf-8 -*-
"""QR code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oDxTc-lsXlRpPMdYShphEdHcRCHFt63i
"""

pip install qrcode

import qrcode
from PIL import Image

qr = qrcode.QRCode(version=1,
                   error_correction=qrcode.constants.ERROR_CORRECT_H,
                   box_size=10,border=10)
qr.add_data("https://www.youtube.com/@JagritiRay-xm1rr/videos")
qr.make(fit=True)
img = qr.make_image(fill_color="red",back_color="white")
img.save("JR_Youtube.png")